context.properties.rules = [
    {
        matches = [
            {
                # Match your FiiO K5 Pro specifically
                node.name = "~alsa_output.usb-FiiO_FiiO_K5_Pro.*"
            }
        ]
        actions = {
            update-props = {
                api.alsa.period-size   = 1024
                api.alsa.headroom      = 0
                api.alsa.disable-mmap  = false
                api.alsa.disable-batch = true
                # Forces the hardware to stay in its best format
                audio.format           = "S32LE" 
            }
        }
    }
]
